// Code generated by ent, DO NOT EDIT.

package securityadvisory

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

const (
	// Label holds the string label denoting the securityadvisory type in the database.
	Label = "security_advisory"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGhsaID holds the string denoting the ghsa_id field in the database.
	FieldGhsaID = "ghsa_id"
	// FieldCveID holds the string denoting the cve_id field in the database.
	FieldCveID = "cve_id"
	// FieldCveYear holds the string denoting the cve_year field in the database.
	FieldCveYear = "cve_year"
	// FieldOsvID holds the string denoting the osv_id field in the database.
	FieldOsvID = "osv_id"
)

// OrderOption defines the ordering options for the SecurityAdvisory queries.
type OrderOption func(*dsl.Traversal)
