// Code generated by ent, DO NOT EDIT.

package artifact

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

const (
	// Label holds the string label denoting the artifact type in the database.
	Label = "artifact"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlgorithm holds the string denoting the algorithm field in the database.
	FieldAlgorithm = "algorithm"
	// FieldDigest holds the string denoting the digest field in the database.
	FieldDigest = "digest"
	// EdgeOccurrences holds the string denoting the occurrences edge name in mutations.
	EdgeOccurrences = "occurrences"
	// EdgeSbom holds the string denoting the sbom edge name in mutations.
	EdgeSbom = "sbom"
	// EdgeAttestations holds the string denoting the attestations edge name in mutations.
	EdgeAttestations = "attestations"
	// EdgeSame holds the string denoting the same edge name in mutations.
	EdgeSame = "same"
	// OccurrencesInverseLabel holds the string label denoting the occurrences inverse edge type in the database.
	OccurrencesInverseLabel = "occurrence_artifact"
	// SbomInverseLabel holds the string label denoting the sbom inverse edge type in the database.
	SbomInverseLabel = "bill_of_materials_artifact"
	// AttestationsInverseLabel holds the string label denoting the attestations inverse edge type in the database.
	AttestationsInverseLabel = "slsa_attestation_built_from"
	// SameInverseLabel holds the string label denoting the same inverse edge type in the database.
	SameInverseLabel = "hash_equal_artifacts"
)

// OrderOption defines the ordering options for the Artifact queries.
type OrderOption func(*dsl.Traversal)
