// Code generated by ent, DO NOT EDIT.

package packagenamespace

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

const (
	// Label holds the string label denoting the packagenamespace type in the database.
	Label = "package_namespace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPackageID holds the string denoting the package_id field in the database.
	FieldPackageID = "package_id"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// EdgePackage holds the string denoting the package edge name in mutations.
	EdgePackage = "package"
	// EdgeNames holds the string denoting the names edge name in mutations.
	EdgeNames = "names"
	// PackageInverseLabel holds the string label denoting the package inverse edge type in the database.
	PackageInverseLabel = "package_type_namespaces"
	// NamesLabel holds the string label denoting the names edge type in the database.
	NamesLabel = "package_namespace_names"
)

// OrderOption defines the ordering options for the PackageNamespace queries.
type OrderOption func(*dsl.Traversal)
