// Code generated by ent, DO NOT EDIT.

package packageversion

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

const (
	// Label holds the string label denoting the packageversion type in the database.
	Label = "package_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameID holds the string denoting the name_id field in the database.
	FieldNameID = "name_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldSubpath holds the string denoting the subpath field in the database.
	FieldSubpath = "subpath"
	// FieldQualifiers holds the string denoting the qualifiers field in the database.
	FieldQualifiers = "qualifiers"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// EdgeName holds the string denoting the name edge name in mutations.
	EdgeName = "name"
	// EdgeOccurrences holds the string denoting the occurrences edge name in mutations.
	EdgeOccurrences = "occurrences"
	// EdgeSbom holds the string denoting the sbom edge name in mutations.
	EdgeSbom = "sbom"
	// EdgeEqualPackages holds the string denoting the equal_packages edge name in mutations.
	EdgeEqualPackages = "equal_packages"
	// NameInverseLabel holds the string label denoting the name inverse edge type in the database.
	NameInverseLabel = "package_name_versions"
	// OccurrencesInverseLabel holds the string label denoting the occurrences inverse edge type in the database.
	OccurrencesInverseLabel = "occurrence_package"
	// SbomInverseLabel holds the string label denoting the sbom inverse edge type in the database.
	SbomInverseLabel = "bill_of_materials_package"
	// EqualPackagesInverseLabel holds the string label denoting the equal_packages inverse edge type in the database.
	EqualPackagesInverseLabel = "pkg_equal_packages"
)

var (
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// DefaultSubpath holds the default value on creation for the "subpath" field.
	DefaultSubpath string
)

// OrderOption defines the ordering options for the PackageVersion queries.
type OrderOption func(*dsl.Traversal)
