// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/certifyscorecard"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// CertifyScorecardDelete is the builder for deleting a CertifyScorecard entity.
type CertifyScorecardDelete struct {
	config
	hooks    []Hook
	mutation *CertifyScorecardMutation
}

// Where appends a list predicates to the CertifyScorecardDelete builder.
func (csd *CertifyScorecardDelete) Where(ps ...predicate.CertifyScorecard) *CertifyScorecardDelete {
	csd.mutation.Where(ps...)
	return csd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csd *CertifyScorecardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, csd.gremlinExec, csd.mutation, csd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (csd *CertifyScorecardDelete) ExecX(ctx context.Context) int {
	n, err := csd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csd *CertifyScorecardDelete) gremlinExec(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := csd.gremlin().Query()
	if err := csd.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	csd.mutation.done = true
	return res.ReadInt()
}

func (csd *CertifyScorecardDelete) gremlin() *dsl.Traversal {
	t := g.V().HasLabel(certifyscorecard.Label)
	for _, p := range csd.mutation.predicates {
		p(t)
	}
	return t.SideEffect(__.Drop()).Count()
}

// CertifyScorecardDeleteOne is the builder for deleting a single CertifyScorecard entity.
type CertifyScorecardDeleteOne struct {
	csd *CertifyScorecardDelete
}

// Where appends a list predicates to the CertifyScorecardDelete builder.
func (csdo *CertifyScorecardDeleteOne) Where(ps ...predicate.CertifyScorecard) *CertifyScorecardDeleteOne {
	csdo.csd.mutation.Where(ps...)
	return csdo
}

// Exec executes the deletion query.
func (csdo *CertifyScorecardDeleteOne) Exec(ctx context.Context) error {
	n, err := csdo.csd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{certifyscorecard.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csdo *CertifyScorecardDeleteOne) ExecX(ctx context.Context) {
	if err := csdo.Exec(ctx); err != nil {
		panic(err)
	}
}
