// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagetype"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// PackageTypeDelete is the builder for deleting a PackageType entity.
type PackageTypeDelete struct {
	config
	hooks    []Hook
	mutation *PackageTypeMutation
}

// Where appends a list predicates to the PackageTypeDelete builder.
func (ptd *PackageTypeDelete) Where(ps ...predicate.PackageType) *PackageTypeDelete {
	ptd.mutation.Where(ps...)
	return ptd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ptd *PackageTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ptd.gremlinExec, ptd.mutation, ptd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ptd *PackageTypeDelete) ExecX(ctx context.Context) int {
	n, err := ptd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ptd *PackageTypeDelete) gremlinExec(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := ptd.gremlin().Query()
	if err := ptd.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	ptd.mutation.done = true
	return res.ReadInt()
}

func (ptd *PackageTypeDelete) gremlin() *dsl.Traversal {
	t := g.V().HasLabel(packagetype.Label)
	for _, p := range ptd.mutation.predicates {
		p(t)
	}
	return t.SideEffect(__.Drop()).Count()
}

// PackageTypeDeleteOne is the builder for deleting a single PackageType entity.
type PackageTypeDeleteOne struct {
	ptd *PackageTypeDelete
}

// Where appends a list predicates to the PackageTypeDelete builder.
func (ptdo *PackageTypeDeleteOne) Where(ps ...predicate.PackageType) *PackageTypeDeleteOne {
	ptdo.ptd.mutation.Where(ps...)
	return ptdo
}

// Exec executes the deletion query.
func (ptdo *PackageTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := ptdo.ptd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{packagetype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ptdo *PackageTypeDeleteOne) ExecX(ctx context.Context) {
	if err := ptdo.Exec(ctx); err != nil {
		panic(err)
	}
}
