// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/pkgequal"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// PkgEqualQuery is the builder for querying PkgEqual entities.
type PkgEqualQuery struct {
	config
	ctx          *QueryContext
	order        []pkgequal.OrderOption
	inters       []Interceptor
	predicates   []predicate.PkgEqual
	withPackages *PackageVersionQuery
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Where adds a new predicate for the PkgEqualQuery builder.
func (peq *PkgEqualQuery) Where(ps ...predicate.PkgEqual) *PkgEqualQuery {
	peq.predicates = append(peq.predicates, ps...)
	return peq
}

// Limit the number of records to be returned by this query.
func (peq *PkgEqualQuery) Limit(limit int) *PkgEqualQuery {
	peq.ctx.Limit = &limit
	return peq
}

// Offset to start from.
func (peq *PkgEqualQuery) Offset(offset int) *PkgEqualQuery {
	peq.ctx.Offset = &offset
	return peq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (peq *PkgEqualQuery) Unique(unique bool) *PkgEqualQuery {
	peq.ctx.Unique = &unique
	return peq
}

// Order specifies how the records should be ordered.
func (peq *PkgEqualQuery) Order(o ...pkgequal.OrderOption) *PkgEqualQuery {
	peq.order = append(peq.order, o...)
	return peq
}

// QueryPackages chains the current query on the "packages" edge.
func (peq *PkgEqualQuery) QueryPackages() *PackageVersionQuery {
	query := (&PackageVersionClient{config: peq.config}).Query()
	query.path = func(ctx context.Context) (fromU *dsl.Traversal, err error) {
		if err := peq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		gremlin := peq.gremlinQuery(ctx)
		fromU = gremlin.OutE(pkgequal.PackagesLabel).InV()
		return fromU, nil
	}
	return query
}

// First returns the first PkgEqual entity from the query.
// Returns a *NotFoundError when no PkgEqual was found.
func (peq *PkgEqualQuery) First(ctx context.Context) (*PkgEqual, error) {
	nodes, err := peq.Limit(1).All(setContextOp(ctx, peq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pkgequal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (peq *PkgEqualQuery) FirstX(ctx context.Context) *PkgEqual {
	node, err := peq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PkgEqual ID from the query.
// Returns a *NotFoundError when no PkgEqual ID was found.
func (peq *PkgEqualQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = peq.Limit(1).IDs(setContextOp(ctx, peq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pkgequal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (peq *PkgEqualQuery) FirstIDX(ctx context.Context) int {
	id, err := peq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PkgEqual entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PkgEqual entity is found.
// Returns a *NotFoundError when no PkgEqual entities are found.
func (peq *PkgEqualQuery) Only(ctx context.Context) (*PkgEqual, error) {
	nodes, err := peq.Limit(2).All(setContextOp(ctx, peq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pkgequal.Label}
	default:
		return nil, &NotSingularError{pkgequal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (peq *PkgEqualQuery) OnlyX(ctx context.Context) *PkgEqual {
	node, err := peq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PkgEqual ID in the query.
// Returns a *NotSingularError when more than one PkgEqual ID is found.
// Returns a *NotFoundError when no entities are found.
func (peq *PkgEqualQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = peq.Limit(2).IDs(setContextOp(ctx, peq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pkgequal.Label}
	default:
		err = &NotSingularError{pkgequal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (peq *PkgEqualQuery) OnlyIDX(ctx context.Context) int {
	id, err := peq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PkgEquals.
func (peq *PkgEqualQuery) All(ctx context.Context) ([]*PkgEqual, error) {
	ctx = setContextOp(ctx, peq.ctx, "All")
	if err := peq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PkgEqual, *PkgEqualQuery]()
	return withInterceptors[[]*PkgEqual](ctx, peq, qr, peq.inters)
}

// AllX is like All, but panics if an error occurs.
func (peq *PkgEqualQuery) AllX(ctx context.Context) []*PkgEqual {
	nodes, err := peq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PkgEqual IDs.
func (peq *PkgEqualQuery) IDs(ctx context.Context) (ids []int, err error) {
	if peq.ctx.Unique == nil && peq.path != nil {
		peq.Unique(true)
	}
	ctx = setContextOp(ctx, peq.ctx, "IDs")
	if err = peq.Select(pkgequal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (peq *PkgEqualQuery) IDsX(ctx context.Context) []int {
	ids, err := peq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (peq *PkgEqualQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, peq.ctx, "Count")
	if err := peq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, peq, querierCount[*PkgEqualQuery](), peq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (peq *PkgEqualQuery) CountX(ctx context.Context) int {
	count, err := peq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (peq *PkgEqualQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, peq.ctx, "Exist")
	switch _, err := peq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (peq *PkgEqualQuery) ExistX(ctx context.Context) bool {
	exist, err := peq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PkgEqualQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (peq *PkgEqualQuery) Clone() *PkgEqualQuery {
	if peq == nil {
		return nil
	}
	return &PkgEqualQuery{
		config:       peq.config,
		ctx:          peq.ctx.Clone(),
		order:        append([]pkgequal.OrderOption{}, peq.order...),
		inters:       append([]Interceptor{}, peq.inters...),
		predicates:   append([]predicate.PkgEqual{}, peq.predicates...),
		withPackages: peq.withPackages.Clone(),
		// clone intermediate query.
		gremlin: peq.gremlin.Clone(),
		path:    peq.path,
	}
}

// WithPackages tells the query-builder to eager-load the nodes that are connected to
// the "packages" edge. The optional arguments are used to configure the query builder of the edge.
func (peq *PkgEqualQuery) WithPackages(opts ...func(*PackageVersionQuery)) *PkgEqualQuery {
	query := (&PackageVersionClient{config: peq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	peq.withPackages = query
	return peq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Origin string `json:"origin,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PkgEqual.Query().
//		GroupBy(pkgequal.FieldOrigin).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (peq *PkgEqualQuery) GroupBy(field string, fields ...string) *PkgEqualGroupBy {
	peq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PkgEqualGroupBy{build: peq}
	grbuild.flds = &peq.ctx.Fields
	grbuild.label = pkgequal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Origin string `json:"origin,omitempty"`
//	}
//
//	client.PkgEqual.Query().
//		Select(pkgequal.FieldOrigin).
//		Scan(ctx, &v)
func (peq *PkgEqualQuery) Select(fields ...string) *PkgEqualSelect {
	peq.ctx.Fields = append(peq.ctx.Fields, fields...)
	sbuild := &PkgEqualSelect{PkgEqualQuery: peq}
	sbuild.label = pkgequal.Label
	sbuild.flds, sbuild.scan = &peq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PkgEqualSelect configured with the given aggregations.
func (peq *PkgEqualQuery) Aggregate(fns ...AggregateFunc) *PkgEqualSelect {
	return peq.Select().Aggregate(fns...)
}

func (peq *PkgEqualQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range peq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, peq); err != nil {
				return err
			}
		}
	}
	if peq.path != nil {
		prev, err := peq.path(ctx)
		if err != nil {
			return err
		}
		peq.gremlin = prev
	}
	return nil
}

func (peq *PkgEqualQuery) gremlinAll(ctx context.Context, hooks ...queryHook) ([]*PkgEqual, error) {
	res := &gremlin.Response{}
	traversal := peq.gremlinQuery(ctx)
	if len(peq.ctx.Fields) > 0 {
		fields := make([]any, len(peq.ctx.Fields))
		for i, f := range peq.ctx.Fields {
			fields[i] = f
		}
		traversal.ValueMap(fields...)
	} else {
		traversal.ValueMap(true)
	}
	query, bindings := traversal.Query()
	if err := peq.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	var pes PkgEquals
	if err := pes.FromResponse(res); err != nil {
		return nil, err
	}
	for i := range pes {
		pes[i].config = peq.config
	}
	return pes, nil
}

func (peq *PkgEqualQuery) gremlinCount(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := peq.gremlinQuery(ctx).Count().Query()
	if err := peq.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (peq *PkgEqualQuery) gremlinQuery(context.Context) *dsl.Traversal {
	v := g.V().HasLabel(pkgequal.Label)
	if peq.gremlin != nil {
		v = peq.gremlin.Clone()
	}
	for _, p := range peq.predicates {
		p(v)
	}
	if len(peq.order) > 0 {
		v.Order()
		for _, p := range peq.order {
			p(v)
		}
	}
	switch limit, offset := peq.ctx.Limit, peq.ctx.Offset; {
	case limit != nil && offset != nil:
		v.Range(*offset, *offset+*limit)
	case offset != nil:
		v.Range(*offset, math.MaxInt32)
	case limit != nil:
		v.Limit(*limit)
	}
	if unique := peq.ctx.Unique; unique == nil || *unique {
		v.Dedup()
	}
	return v
}

// PkgEqualGroupBy is the group-by builder for PkgEqual entities.
type PkgEqualGroupBy struct {
	selector
	build *PkgEqualQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pegb *PkgEqualGroupBy) Aggregate(fns ...AggregateFunc) *PkgEqualGroupBy {
	pegb.fns = append(pegb.fns, fns...)
	return pegb
}

// Scan applies the selector query and scans the result into the given value.
func (pegb *PkgEqualGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pegb.build.ctx, "GroupBy")
	if err := pegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PkgEqualQuery, *PkgEqualGroupBy](ctx, pegb.build, pegb, pegb.build.inters, v)
}

func (pegb *PkgEqualGroupBy) gremlinScan(ctx context.Context, root *PkgEqualQuery, v any) error {
	var (
		trs   []any
		names []any
	)
	for _, fn := range pegb.fns {
		name, tr := fn("p", "")
		trs = append(trs, tr)
		names = append(names, name)
	}
	for _, f := range *pegb.flds {
		names = append(names, f)
		trs = append(trs, __.As("p").Unfold().Values(f).As(f))
	}
	query, bindings := root.gremlinQuery(ctx).Group().
		By(__.Values(*pegb.flds...).Fold()).
		By(__.Fold().Match(trs...).Select(names...)).
		Select(dsl.Values).
		Next().
		Query()
	res := &gremlin.Response{}
	if err := pegb.build.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(*pegb.flds)+len(pegb.fns) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}

// PkgEqualSelect is the builder for selecting fields of PkgEqual entities.
type PkgEqualSelect struct {
	*PkgEqualQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pes *PkgEqualSelect) Aggregate(fns ...AggregateFunc) *PkgEqualSelect {
	pes.fns = append(pes.fns, fns...)
	return pes
}

// Scan applies the selector query and scans the result into the given value.
func (pes *PkgEqualSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pes.ctx, "Select")
	if err := pes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PkgEqualQuery, *PkgEqualSelect](ctx, pes.PkgEqualQuery, pes, pes.inters, v)
}

func (pes *PkgEqualSelect) gremlinScan(ctx context.Context, root *PkgEqualQuery, v any) error {
	var (
		res       = &gremlin.Response{}
		traversal = root.gremlinQuery(ctx)
	)
	if fields := pes.ctx.Fields; len(fields) == 1 {
		if fields[0] != pkgequal.FieldID {
			traversal = traversal.Values(fields...)
		} else {
			traversal = traversal.ID()
		}
	} else {
		fields := make([]any, len(pes.ctx.Fields))
		for i, f := range pes.ctx.Fields {
			fields[i] = f
		}
		traversal = traversal.ValueMap(fields...)
	}
	query, bindings := traversal.Query()
	if err := pes.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(root.ctx.Fields) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}
