// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/securityadvisory"
)

// SecurityAdvisoryDelete is the builder for deleting a SecurityAdvisory entity.
type SecurityAdvisoryDelete struct {
	config
	hooks    []Hook
	mutation *SecurityAdvisoryMutation
}

// Where appends a list predicates to the SecurityAdvisoryDelete builder.
func (sad *SecurityAdvisoryDelete) Where(ps ...predicate.SecurityAdvisory) *SecurityAdvisoryDelete {
	sad.mutation.Where(ps...)
	return sad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sad *SecurityAdvisoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sad.gremlinExec, sad.mutation, sad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sad *SecurityAdvisoryDelete) ExecX(ctx context.Context) int {
	n, err := sad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sad *SecurityAdvisoryDelete) gremlinExec(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := sad.gremlin().Query()
	if err := sad.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	sad.mutation.done = true
	return res.ReadInt()
}

func (sad *SecurityAdvisoryDelete) gremlin() *dsl.Traversal {
	t := g.V().HasLabel(securityadvisory.Label)
	for _, p := range sad.mutation.predicates {
		p(t)
	}
	return t.SideEffect(__.Drop()).Count()
}

// SecurityAdvisoryDeleteOne is the builder for deleting a single SecurityAdvisory entity.
type SecurityAdvisoryDeleteOne struct {
	sad *SecurityAdvisoryDelete
}

// Where appends a list predicates to the SecurityAdvisoryDelete builder.
func (sado *SecurityAdvisoryDeleteOne) Where(ps ...predicate.SecurityAdvisory) *SecurityAdvisoryDeleteOne {
	sado.sad.mutation.Where(ps...)
	return sado
}

// Exec executes the deletion query.
func (sado *SecurityAdvisoryDeleteOne) Exec(ctx context.Context) error {
	n, err := sado.sad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{securityadvisory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sado *SecurityAdvisoryDeleteOne) ExecX(ctx context.Context) {
	if err := sado.Exec(ctx); err != nil {
		panic(err)
	}
}
