// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sourcename"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sourcenamespace"
)

// SourceNamespaceQuery is the builder for querying SourceNamespace entities.
type SourceNamespaceQuery struct {
	config
	ctx            *QueryContext
	order          []sourcenamespace.OrderOption
	inters         []Interceptor
	predicates     []predicate.SourceNamespace
	withSourceType *SourceTypeQuery
	withNames      *SourceNameQuery
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Where adds a new predicate for the SourceNamespaceQuery builder.
func (snq *SourceNamespaceQuery) Where(ps ...predicate.SourceNamespace) *SourceNamespaceQuery {
	snq.predicates = append(snq.predicates, ps...)
	return snq
}

// Limit the number of records to be returned by this query.
func (snq *SourceNamespaceQuery) Limit(limit int) *SourceNamespaceQuery {
	snq.ctx.Limit = &limit
	return snq
}

// Offset to start from.
func (snq *SourceNamespaceQuery) Offset(offset int) *SourceNamespaceQuery {
	snq.ctx.Offset = &offset
	return snq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (snq *SourceNamespaceQuery) Unique(unique bool) *SourceNamespaceQuery {
	snq.ctx.Unique = &unique
	return snq
}

// Order specifies how the records should be ordered.
func (snq *SourceNamespaceQuery) Order(o ...sourcenamespace.OrderOption) *SourceNamespaceQuery {
	snq.order = append(snq.order, o...)
	return snq
}

// QuerySourceType chains the current query on the "source_type" edge.
func (snq *SourceNamespaceQuery) QuerySourceType() *SourceTypeQuery {
	query := (&SourceTypeClient{config: snq.config}).Query()
	query.path = func(ctx context.Context) (fromU *dsl.Traversal, err error) {
		if err := snq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		gremlin := snq.gremlinQuery(ctx)
		fromU = gremlin.OutE(sourcenamespace.SourceTypeLabel).InV()
		return fromU, nil
	}
	return query
}

// QueryNames chains the current query on the "names" edge.
func (snq *SourceNamespaceQuery) QueryNames() *SourceNameQuery {
	query := (&SourceNameClient{config: snq.config}).Query()
	query.path = func(ctx context.Context) (fromU *dsl.Traversal, err error) {
		if err := snq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		gremlin := snq.gremlinQuery(ctx)
		fromU = gremlin.InE(sourcename.NamespaceLabel).OutV()
		return fromU, nil
	}
	return query
}

// First returns the first SourceNamespace entity from the query.
// Returns a *NotFoundError when no SourceNamespace was found.
func (snq *SourceNamespaceQuery) First(ctx context.Context) (*SourceNamespace, error) {
	nodes, err := snq.Limit(1).All(setContextOp(ctx, snq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sourcenamespace.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (snq *SourceNamespaceQuery) FirstX(ctx context.Context) *SourceNamespace {
	node, err := snq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SourceNamespace ID from the query.
// Returns a *NotFoundError when no SourceNamespace ID was found.
func (snq *SourceNamespaceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = snq.Limit(1).IDs(setContextOp(ctx, snq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sourcenamespace.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (snq *SourceNamespaceQuery) FirstIDX(ctx context.Context) int {
	id, err := snq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SourceNamespace entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SourceNamespace entity is found.
// Returns a *NotFoundError when no SourceNamespace entities are found.
func (snq *SourceNamespaceQuery) Only(ctx context.Context) (*SourceNamespace, error) {
	nodes, err := snq.Limit(2).All(setContextOp(ctx, snq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sourcenamespace.Label}
	default:
		return nil, &NotSingularError{sourcenamespace.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (snq *SourceNamespaceQuery) OnlyX(ctx context.Context) *SourceNamespace {
	node, err := snq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SourceNamespace ID in the query.
// Returns a *NotSingularError when more than one SourceNamespace ID is found.
// Returns a *NotFoundError when no entities are found.
func (snq *SourceNamespaceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = snq.Limit(2).IDs(setContextOp(ctx, snq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sourcenamespace.Label}
	default:
		err = &NotSingularError{sourcenamespace.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (snq *SourceNamespaceQuery) OnlyIDX(ctx context.Context) int {
	id, err := snq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SourceNamespaces.
func (snq *SourceNamespaceQuery) All(ctx context.Context) ([]*SourceNamespace, error) {
	ctx = setContextOp(ctx, snq.ctx, "All")
	if err := snq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SourceNamespace, *SourceNamespaceQuery]()
	return withInterceptors[[]*SourceNamespace](ctx, snq, qr, snq.inters)
}

// AllX is like All, but panics if an error occurs.
func (snq *SourceNamespaceQuery) AllX(ctx context.Context) []*SourceNamespace {
	nodes, err := snq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SourceNamespace IDs.
func (snq *SourceNamespaceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if snq.ctx.Unique == nil && snq.path != nil {
		snq.Unique(true)
	}
	ctx = setContextOp(ctx, snq.ctx, "IDs")
	if err = snq.Select(sourcenamespace.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (snq *SourceNamespaceQuery) IDsX(ctx context.Context) []int {
	ids, err := snq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (snq *SourceNamespaceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, snq.ctx, "Count")
	if err := snq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, snq, querierCount[*SourceNamespaceQuery](), snq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (snq *SourceNamespaceQuery) CountX(ctx context.Context) int {
	count, err := snq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (snq *SourceNamespaceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, snq.ctx, "Exist")
	switch _, err := snq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (snq *SourceNamespaceQuery) ExistX(ctx context.Context) bool {
	exist, err := snq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SourceNamespaceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (snq *SourceNamespaceQuery) Clone() *SourceNamespaceQuery {
	if snq == nil {
		return nil
	}
	return &SourceNamespaceQuery{
		config:         snq.config,
		ctx:            snq.ctx.Clone(),
		order:          append([]sourcenamespace.OrderOption{}, snq.order...),
		inters:         append([]Interceptor{}, snq.inters...),
		predicates:     append([]predicate.SourceNamespace{}, snq.predicates...),
		withSourceType: snq.withSourceType.Clone(),
		withNames:      snq.withNames.Clone(),
		// clone intermediate query.
		gremlin: snq.gremlin.Clone(),
		path:    snq.path,
	}
}

// WithSourceType tells the query-builder to eager-load the nodes that are connected to
// the "source_type" edge. The optional arguments are used to configure the query builder of the edge.
func (snq *SourceNamespaceQuery) WithSourceType(opts ...func(*SourceTypeQuery)) *SourceNamespaceQuery {
	query := (&SourceTypeClient{config: snq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	snq.withSourceType = query
	return snq
}

// WithNames tells the query-builder to eager-load the nodes that are connected to
// the "names" edge. The optional arguments are used to configure the query builder of the edge.
func (snq *SourceNamespaceQuery) WithNames(opts ...func(*SourceNameQuery)) *SourceNamespaceQuery {
	query := (&SourceNameClient{config: snq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	snq.withNames = query
	return snq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Namespace string `json:"namespace,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SourceNamespace.Query().
//		GroupBy(sourcenamespace.FieldNamespace).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (snq *SourceNamespaceQuery) GroupBy(field string, fields ...string) *SourceNamespaceGroupBy {
	snq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SourceNamespaceGroupBy{build: snq}
	grbuild.flds = &snq.ctx.Fields
	grbuild.label = sourcenamespace.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Namespace string `json:"namespace,omitempty"`
//	}
//
//	client.SourceNamespace.Query().
//		Select(sourcenamespace.FieldNamespace).
//		Scan(ctx, &v)
func (snq *SourceNamespaceQuery) Select(fields ...string) *SourceNamespaceSelect {
	snq.ctx.Fields = append(snq.ctx.Fields, fields...)
	sbuild := &SourceNamespaceSelect{SourceNamespaceQuery: snq}
	sbuild.label = sourcenamespace.Label
	sbuild.flds, sbuild.scan = &snq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SourceNamespaceSelect configured with the given aggregations.
func (snq *SourceNamespaceQuery) Aggregate(fns ...AggregateFunc) *SourceNamespaceSelect {
	return snq.Select().Aggregate(fns...)
}

func (snq *SourceNamespaceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range snq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, snq); err != nil {
				return err
			}
		}
	}
	if snq.path != nil {
		prev, err := snq.path(ctx)
		if err != nil {
			return err
		}
		snq.gremlin = prev
	}
	return nil
}

func (snq *SourceNamespaceQuery) gremlinAll(ctx context.Context, hooks ...queryHook) ([]*SourceNamespace, error) {
	res := &gremlin.Response{}
	traversal := snq.gremlinQuery(ctx)
	if len(snq.ctx.Fields) > 0 {
		fields := make([]any, len(snq.ctx.Fields))
		for i, f := range snq.ctx.Fields {
			fields[i] = f
		}
		traversal.ValueMap(fields...)
	} else {
		traversal.ValueMap(true)
	}
	query, bindings := traversal.Query()
	if err := snq.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	var sns SourceNamespaces
	if err := sns.FromResponse(res); err != nil {
		return nil, err
	}
	for i := range sns {
		sns[i].config = snq.config
	}
	return sns, nil
}

func (snq *SourceNamespaceQuery) gremlinCount(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := snq.gremlinQuery(ctx).Count().Query()
	if err := snq.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (snq *SourceNamespaceQuery) gremlinQuery(context.Context) *dsl.Traversal {
	v := g.V().HasLabel(sourcenamespace.Label)
	if snq.gremlin != nil {
		v = snq.gremlin.Clone()
	}
	for _, p := range snq.predicates {
		p(v)
	}
	if len(snq.order) > 0 {
		v.Order()
		for _, p := range snq.order {
			p(v)
		}
	}
	switch limit, offset := snq.ctx.Limit, snq.ctx.Offset; {
	case limit != nil && offset != nil:
		v.Range(*offset, *offset+*limit)
	case offset != nil:
		v.Range(*offset, math.MaxInt32)
	case limit != nil:
		v.Limit(*limit)
	}
	if unique := snq.ctx.Unique; unique == nil || *unique {
		v.Dedup()
	}
	return v
}

// SourceNamespaceGroupBy is the group-by builder for SourceNamespace entities.
type SourceNamespaceGroupBy struct {
	selector
	build *SourceNamespaceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sngb *SourceNamespaceGroupBy) Aggregate(fns ...AggregateFunc) *SourceNamespaceGroupBy {
	sngb.fns = append(sngb.fns, fns...)
	return sngb
}

// Scan applies the selector query and scans the result into the given value.
func (sngb *SourceNamespaceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sngb.build.ctx, "GroupBy")
	if err := sngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceNamespaceQuery, *SourceNamespaceGroupBy](ctx, sngb.build, sngb, sngb.build.inters, v)
}

func (sngb *SourceNamespaceGroupBy) gremlinScan(ctx context.Context, root *SourceNamespaceQuery, v any) error {
	var (
		trs   []any
		names []any
	)
	for _, fn := range sngb.fns {
		name, tr := fn("p", "")
		trs = append(trs, tr)
		names = append(names, name)
	}
	for _, f := range *sngb.flds {
		names = append(names, f)
		trs = append(trs, __.As("p").Unfold().Values(f).As(f))
	}
	query, bindings := root.gremlinQuery(ctx).Group().
		By(__.Values(*sngb.flds...).Fold()).
		By(__.Fold().Match(trs...).Select(names...)).
		Select(dsl.Values).
		Next().
		Query()
	res := &gremlin.Response{}
	if err := sngb.build.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(*sngb.flds)+len(sngb.fns) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}

// SourceNamespaceSelect is the builder for selecting fields of SourceNamespace entities.
type SourceNamespaceSelect struct {
	*SourceNamespaceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sns *SourceNamespaceSelect) Aggregate(fns ...AggregateFunc) *SourceNamespaceSelect {
	sns.fns = append(sns.fns, fns...)
	return sns
}

// Scan applies the selector query and scans the result into the given value.
func (sns *SourceNamespaceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sns.ctx, "Select")
	if err := sns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceNamespaceQuery, *SourceNamespaceSelect](ctx, sns.SourceNamespaceQuery, sns, sns.inters, v)
}

func (sns *SourceNamespaceSelect) gremlinScan(ctx context.Context, root *SourceNamespaceQuery, v any) error {
	var (
		res       = &gremlin.Response{}
		traversal = root.gremlinQuery(ctx)
	)
	if fields := sns.ctx.Fields; len(fields) == 1 {
		if fields[0] != sourcenamespace.FieldID {
			traversal = traversal.Values(fields...)
		} else {
			traversal = traversal.ID()
		}
	} else {
		fields := make([]any, len(sns.ctx.Fields))
		for i, f := range sns.ctx.Fields {
			fields[i] = f
		}
		traversal = traversal.ValueMap(fields...)
	}
	query, bindings := traversal.Query()
	if err := sns.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(root.ctx.Fields) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}
