// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/gremlin"
	"entgo.io/ent/dialect/gremlin/graph/dsl"
	"entgo.io/ent/dialect/gremlin/graph/dsl/__"
	"entgo.io/ent/dialect/gremlin/graph/dsl/g"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sourcenamespace"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sourcetype"
)

// SourceTypeQuery is the builder for querying SourceType entities.
type SourceTypeQuery struct {
	config
	ctx            *QueryContext
	order          []sourcetype.OrderOption
	inters         []Interceptor
	predicates     []predicate.SourceType
	withNamespaces *SourceNamespaceQuery
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Where adds a new predicate for the SourceTypeQuery builder.
func (stq *SourceTypeQuery) Where(ps ...predicate.SourceType) *SourceTypeQuery {
	stq.predicates = append(stq.predicates, ps...)
	return stq
}

// Limit the number of records to be returned by this query.
func (stq *SourceTypeQuery) Limit(limit int) *SourceTypeQuery {
	stq.ctx.Limit = &limit
	return stq
}

// Offset to start from.
func (stq *SourceTypeQuery) Offset(offset int) *SourceTypeQuery {
	stq.ctx.Offset = &offset
	return stq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stq *SourceTypeQuery) Unique(unique bool) *SourceTypeQuery {
	stq.ctx.Unique = &unique
	return stq
}

// Order specifies how the records should be ordered.
func (stq *SourceTypeQuery) Order(o ...sourcetype.OrderOption) *SourceTypeQuery {
	stq.order = append(stq.order, o...)
	return stq
}

// QueryNamespaces chains the current query on the "namespaces" edge.
func (stq *SourceTypeQuery) QueryNamespaces() *SourceNamespaceQuery {
	query := (&SourceNamespaceClient{config: stq.config}).Query()
	query.path = func(ctx context.Context) (fromU *dsl.Traversal, err error) {
		if err := stq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		gremlin := stq.gremlinQuery(ctx)
		fromU = gremlin.InE(sourcenamespace.SourceTypeLabel).OutV()
		return fromU, nil
	}
	return query
}

// First returns the first SourceType entity from the query.
// Returns a *NotFoundError when no SourceType was found.
func (stq *SourceTypeQuery) First(ctx context.Context) (*SourceType, error) {
	nodes, err := stq.Limit(1).All(setContextOp(ctx, stq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sourcetype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stq *SourceTypeQuery) FirstX(ctx context.Context) *SourceType {
	node, err := stq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SourceType ID from the query.
// Returns a *NotFoundError when no SourceType ID was found.
func (stq *SourceTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(1).IDs(setContextOp(ctx, stq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sourcetype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stq *SourceTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := stq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SourceType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SourceType entity is found.
// Returns a *NotFoundError when no SourceType entities are found.
func (stq *SourceTypeQuery) Only(ctx context.Context) (*SourceType, error) {
	nodes, err := stq.Limit(2).All(setContextOp(ctx, stq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sourcetype.Label}
	default:
		return nil, &NotSingularError{sourcetype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stq *SourceTypeQuery) OnlyX(ctx context.Context) *SourceType {
	node, err := stq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SourceType ID in the query.
// Returns a *NotSingularError when more than one SourceType ID is found.
// Returns a *NotFoundError when no entities are found.
func (stq *SourceTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(2).IDs(setContextOp(ctx, stq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sourcetype.Label}
	default:
		err = &NotSingularError{sourcetype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stq *SourceTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := stq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SourceTypes.
func (stq *SourceTypeQuery) All(ctx context.Context) ([]*SourceType, error) {
	ctx = setContextOp(ctx, stq.ctx, "All")
	if err := stq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SourceType, *SourceTypeQuery]()
	return withInterceptors[[]*SourceType](ctx, stq, qr, stq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stq *SourceTypeQuery) AllX(ctx context.Context) []*SourceType {
	nodes, err := stq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SourceType IDs.
func (stq *SourceTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if stq.ctx.Unique == nil && stq.path != nil {
		stq.Unique(true)
	}
	ctx = setContextOp(ctx, stq.ctx, "IDs")
	if err = stq.Select(sourcetype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stq *SourceTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := stq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stq *SourceTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stq.ctx, "Count")
	if err := stq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stq, querierCount[*SourceTypeQuery](), stq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stq *SourceTypeQuery) CountX(ctx context.Context) int {
	count, err := stq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stq *SourceTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stq.ctx, "Exist")
	switch _, err := stq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stq *SourceTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := stq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SourceTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stq *SourceTypeQuery) Clone() *SourceTypeQuery {
	if stq == nil {
		return nil
	}
	return &SourceTypeQuery{
		config:         stq.config,
		ctx:            stq.ctx.Clone(),
		order:          append([]sourcetype.OrderOption{}, stq.order...),
		inters:         append([]Interceptor{}, stq.inters...),
		predicates:     append([]predicate.SourceType{}, stq.predicates...),
		withNamespaces: stq.withNamespaces.Clone(),
		// clone intermediate query.
		gremlin: stq.gremlin.Clone(),
		path:    stq.path,
	}
}

// WithNamespaces tells the query-builder to eager-load the nodes that are connected to
// the "namespaces" edge. The optional arguments are used to configure the query builder of the edge.
func (stq *SourceTypeQuery) WithNamespaces(opts ...func(*SourceNamespaceQuery)) *SourceTypeQuery {
	query := (&SourceNamespaceClient{config: stq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	stq.withNamespaces = query
	return stq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SourceType.Query().
//		GroupBy(sourcetype.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (stq *SourceTypeQuery) GroupBy(field string, fields ...string) *SourceTypeGroupBy {
	stq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SourceTypeGroupBy{build: stq}
	grbuild.flds = &stq.ctx.Fields
	grbuild.label = sourcetype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.SourceType.Query().
//		Select(sourcetype.FieldType).
//		Scan(ctx, &v)
func (stq *SourceTypeQuery) Select(fields ...string) *SourceTypeSelect {
	stq.ctx.Fields = append(stq.ctx.Fields, fields...)
	sbuild := &SourceTypeSelect{SourceTypeQuery: stq}
	sbuild.label = sourcetype.Label
	sbuild.flds, sbuild.scan = &stq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SourceTypeSelect configured with the given aggregations.
func (stq *SourceTypeQuery) Aggregate(fns ...AggregateFunc) *SourceTypeSelect {
	return stq.Select().Aggregate(fns...)
}

func (stq *SourceTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stq); err != nil {
				return err
			}
		}
	}
	if stq.path != nil {
		prev, err := stq.path(ctx)
		if err != nil {
			return err
		}
		stq.gremlin = prev
	}
	return nil
}

func (stq *SourceTypeQuery) gremlinAll(ctx context.Context, hooks ...queryHook) ([]*SourceType, error) {
	res := &gremlin.Response{}
	traversal := stq.gremlinQuery(ctx)
	if len(stq.ctx.Fields) > 0 {
		fields := make([]any, len(stq.ctx.Fields))
		for i, f := range stq.ctx.Fields {
			fields[i] = f
		}
		traversal.ValueMap(fields...)
	} else {
		traversal.ValueMap(true)
	}
	query, bindings := traversal.Query()
	if err := stq.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	var sts SourceTypes
	if err := sts.FromResponse(res); err != nil {
		return nil, err
	}
	for i := range sts {
		sts[i].config = stq.config
	}
	return sts, nil
}

func (stq *SourceTypeQuery) gremlinCount(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := stq.gremlinQuery(ctx).Count().Query()
	if err := stq.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (stq *SourceTypeQuery) gremlinQuery(context.Context) *dsl.Traversal {
	v := g.V().HasLabel(sourcetype.Label)
	if stq.gremlin != nil {
		v = stq.gremlin.Clone()
	}
	for _, p := range stq.predicates {
		p(v)
	}
	if len(stq.order) > 0 {
		v.Order()
		for _, p := range stq.order {
			p(v)
		}
	}
	switch limit, offset := stq.ctx.Limit, stq.ctx.Offset; {
	case limit != nil && offset != nil:
		v.Range(*offset, *offset+*limit)
	case offset != nil:
		v.Range(*offset, math.MaxInt32)
	case limit != nil:
		v.Limit(*limit)
	}
	if unique := stq.ctx.Unique; unique == nil || *unique {
		v.Dedup()
	}
	return v
}

// SourceTypeGroupBy is the group-by builder for SourceType entities.
type SourceTypeGroupBy struct {
	selector
	build *SourceTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stgb *SourceTypeGroupBy) Aggregate(fns ...AggregateFunc) *SourceTypeGroupBy {
	stgb.fns = append(stgb.fns, fns...)
	return stgb
}

// Scan applies the selector query and scans the result into the given value.
func (stgb *SourceTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stgb.build.ctx, "GroupBy")
	if err := stgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceTypeQuery, *SourceTypeGroupBy](ctx, stgb.build, stgb, stgb.build.inters, v)
}

func (stgb *SourceTypeGroupBy) gremlinScan(ctx context.Context, root *SourceTypeQuery, v any) error {
	var (
		trs   []any
		names []any
	)
	for _, fn := range stgb.fns {
		name, tr := fn("p", "")
		trs = append(trs, tr)
		names = append(names, name)
	}
	for _, f := range *stgb.flds {
		names = append(names, f)
		trs = append(trs, __.As("p").Unfold().Values(f).As(f))
	}
	query, bindings := root.gremlinQuery(ctx).Group().
		By(__.Values(*stgb.flds...).Fold()).
		By(__.Fold().Match(trs...).Select(names...)).
		Select(dsl.Values).
		Next().
		Query()
	res := &gremlin.Response{}
	if err := stgb.build.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(*stgb.flds)+len(stgb.fns) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}

// SourceTypeSelect is the builder for selecting fields of SourceType entities.
type SourceTypeSelect struct {
	*SourceTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sts *SourceTypeSelect) Aggregate(fns ...AggregateFunc) *SourceTypeSelect {
	sts.fns = append(sts.fns, fns...)
	return sts
}

// Scan applies the selector query and scans the result into the given value.
func (sts *SourceTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sts.ctx, "Select")
	if err := sts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceTypeQuery, *SourceTypeSelect](ctx, sts.SourceTypeQuery, sts, sts.inters, v)
}

func (sts *SourceTypeSelect) gremlinScan(ctx context.Context, root *SourceTypeQuery, v any) error {
	var (
		res       = &gremlin.Response{}
		traversal = root.gremlinQuery(ctx)
	)
	if fields := sts.ctx.Fields; len(fields) == 1 {
		if fields[0] != sourcetype.FieldID {
			traversal = traversal.Values(fields...)
		} else {
			traversal = traversal.ID()
		}
	} else {
		fields := make([]any, len(sts.ctx.Fields))
		for i, f := range sts.ctx.Fields {
			fields[i] = f
		}
		traversal = traversal.ValueMap(fields...)
	}
	query, bindings := traversal.Query()
	if err := sts.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(root.ctx.Fields) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}
