// Code generated by ent, DO NOT EDIT.

package certifyvuln

import (
	"entgo.io/ent/dialect/gremlin/graph/dsl"
)

const (
	// Label holds the string label denoting the certifyvuln type in the database.
	Label = "certify_vuln"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVulnerabilityID holds the string denoting the vulnerability_id field in the database.
	FieldVulnerabilityID = "vulnerability_id"
	// FieldPackageID holds the string denoting the package_id field in the database.
	FieldPackageID = "package_id"
	// FieldTimeScanned holds the string denoting the time_scanned field in the database.
	FieldTimeScanned = "time_scanned"
	// FieldDbURI holds the string denoting the db_uri field in the database.
	FieldDbURI = "db_uri"
	// FieldDbVersion holds the string denoting the db_version field in the database.
	FieldDbVersion = "db_version"
	// FieldScannerURI holds the string denoting the scanner_uri field in the database.
	FieldScannerURI = "scanner_uri"
	// FieldScannerVersion holds the string denoting the scanner_version field in the database.
	FieldScannerVersion = "scanner_version"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// FieldCollector holds the string denoting the collector field in the database.
	FieldCollector = "collector"
	// EdgeVulnerability holds the string denoting the vulnerability edge name in mutations.
	EdgeVulnerability = "vulnerability"
	// EdgePackage holds the string denoting the package edge name in mutations.
	EdgePackage = "package"
	// VulnerabilityLabel holds the string label denoting the vulnerability edge type in the database.
	VulnerabilityLabel = "certify_vuln_vulnerability"
	// PackageLabel holds the string label denoting the package edge type in the database.
	PackageLabel = "certify_vuln_package"
)

// OrderOption defines the ordering options for the CertifyVuln queries.
type OrderOption func(*dsl.Traversal)
